import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import { ThemeProvider } from "@/hooks/themes-provider";
import Header from "@/components/custom/site/header";
import Footer from "@/components/custom/site/footer";


export const metadata: Metadata = {
  title: "Plura Status",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
          className={`bg-background font-sans min-h-screen  ${GeistSans.variable} antialiased`}
        >
        <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <div className="flex flex-col items-center w-full border-border/40 dark:border-border min-[1800px]:max-w-[1536px] min-[1800px]:border-x">
              <Header/>
              {children}
              <Footer/>
            </div>
          </ThemeProvider>
      </body>
    </html>
  );
}
