import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/hooks/theme-provider";
import { PosthogProvider } from "@/hooks/posthog";
import { Toaster } from "sonner";
import { Monitoring } from "react-scan/monitoring/next";
import { cn } from "@/lib/utils";
import { GeistSans } from "geist/font/sans";
import { GeistMono } from "geist/font/mono";

export const metadata: Metadata = {
  title: "Plura",
  description: "Generated by create next app",
};

async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <PosthogProvider>
        <body
          className={cn(
            `min-h-screen bg-background font-sans`,
            GeistSans.variable,
            GeistMono.variable,
          )}
        >
          <Monitoring
            apiKey="TEbNIGehwMWj3N72CP-5eDGwOZC4G8z0"
            url="https://monitoring.react-scan.com/api/v1/ingest"
          />
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <Toaster />
            {children}
          </ThemeProvider>
        </body>
      </PosthogProvider>
    </html>
  );
}

export default RootLayout;
