import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import { ThemeProvider } from "@/hooks/theme-provider";
import { SidebarProvider } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/custom/sidebar/sidebar";
import { cookies } from "next/headers";
import Infobar from "@/components/custom/infobar/infobar";
import ProgressBar from "@/components/custom/progress.bar";
import { PosthogProvider } from "@/hooks/posthog";

export const metadata: Metadata = {
  title: "Plura",
  description: "Generated by create next app",
};

async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("plura-sidebar:state")?.value === "true";

  return (
    <html lang="en" suppressHydrationWarning>
      <PosthogProvider>
        <body
          className={`min-h-screen bg-background font-sans ${GeistSans.variable} antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <SidebarProvider defaultOpen={defaultOpen}>
              <AppSidebar />
              <div className="p-2">
                <ProgressBar />
                <Infobar />
                {children}
              </div>
            </SidebarProvider>
          </ThemeProvider>
        </body>
      </PosthogProvider>
    </html>
  );
}

export default RootLayout;
