export const pricingCardConfig = [
  {
    name: "Basic",
    isFeatured: false,
    isFree: true,
    currency: "$",
    btn: "Get Plura Basic",
    priceMonthly: 0,
    priceYearly: 0,
    beforePriceMonthly: 19,
    beforePriceYearly: 19,
    discountYearly: 100,
    discountMonthly: 100,
    benifits: [
      "1 year access to all the premium component packs and templates",
      "1 year of updates and new features",
      "1 year access to new templates and components",
      "Access to private discord community",
      "48 hours turnaround time for support",
      "Copy and paste, no complexity",
      "Built with Next.js and React",
      "Styled with Tailwind CSS and Framer Motion",
      "Available in TypeScript and JavaScript",
      "Cancel anytime",
    ],
  },

  {
    name: "Plus",
    isFeatured: true,
    isFree: false,
    currency: "$",
    btn: "Get Plura Plus",
    priceMonthly: 29,
    priceYearly: 279,
    beforePriceMonthly: 69,
    beforePriceYearly: 69,
    discountYearly: 60.6,
    discountMonthly: 42.3,
    benifits: [
      "1 year access to all the premium component packs and templates",
      "1 year of updates and new features",
      "1 year access to new templates and components",
      "Access to private discord community",
      "48 hours turnaround time for support",
      "Copy and paste, no complexity",
      "Built with Next.js and React",
      "Styled with Tailwind CSS and Framer Motion",
      "Available in TypeScript and JavaScript",
      "Cancel anytime",
    ],
  },

  {
    name: "Pro",
    isFeatured: false,
    isFree: false,
    currency: "$",
    btn: "Get Plura Pro",
    priceMonthly: 249,
    priceYearly: 679,
    beforePriceMonthly: 629,
    beforePriceYearly: 659,
    discountYearly: 334.03,
    discountMonthly: 423.03,
    benifits: [
      "1 year access to all the premium component packs and templates",
      "1 year of updates and new features",
      "1 year access to new templates and components",
      "Access to private discord community",
      "48 hours turnaround time for support",
      "Copy and paste, no complexity",
      "Built with Next.js and React",
      "Styled with Tailwind CSS and Framer Motion",
      "Available in TypeScript and JavaScript",
      "Cancel anytime",
    ],
  },
];
