export const pricingCardConfig = {
  basic: {
    name: "Basic",
    tier: "Free Lifetime",
    discount: "",
    beforePrice: "",
    currency: "",
    price: "Free",
    features: [
      "1 year access to all the premium component packs and templates",
      "1 year of updates and new features",
      "1 year access to new templates and components",
      "Access to private discord community",
      "48 hours turnaround time for support",
      "Copy and paste, no complexity",
      "Built with Next.js and React",
      "Styled with Tailwind CSS and Framer Motion",
      "Available in TypeScript and JavaScript",
      "Cancel anytime",
    ],
    pros: [],
    cons: [],
  },

  plus: {
    name: "Plus",
    tier: "Paid Monthly",
    discount: "42.03% OFF",
    beforePrice: 69,
    currency: "$",
    price: 29,
    features: [
      "1 year access to all the premium component packs and templates",
      "1 year of updates and new features",
      "1 year access to new templates and components",
      "Access to private discord community",
      "48 hours turnaround time for support",
      "Copy and paste, no complexity",
      "Built with Next.js and React",
      "Styled with Tailwind CSS and Framer Motion",
      "Available in TypeScript and JavaScript",
      "Cancel anytime",
    ],
    pros: [],
    cons: [],
  },

  pro: {
    name: "Pro",
    tier: "Paid Quarterly",
    discount: "55% OFF",
    beforePrice: 449,
    currency: "$",
    price: 249,
    features: [
      "1 year access to all the premium component packs and templates",
      "1 year of updates and new features",
      "1 year access to new templates and components",
      "Access to private discord community",
      "48 hours turnaround time for support",
      "Copy and paste, no complexity",
      "Built with Next.js and React",
      "Styled with Tailwind CSS and Framer Motion",
      "Available in TypeScript and JavaScript",
      "Cancel anytime",
    ],
    pros: [],
    cons: [],
  },
};
